version: '3.1'

services:

  db:
    # Use 10.7 for compatibility with Aurora Serverless Postgres
    image: mdillon/postgis:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supportal
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:5.0.5
    ports:
      - 6379:6379

volumes:
  pgdata: {}
